//
//  CharactersListModel.swift
//  MarvelAPIListSample
//
//  Created by marco.iniguez.ollero on 5/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum CharactersListModel {
  
  enum Request {
    case prepareCharactersList(page: Int)
  }
  
  enum Response {
    case prepareCharactersList(data: [ResultList])
    case showError(model: ErrorModel)
  }
  
  enum ViewModel {
    case showError(model: ErrorModel)
    case prepareCharactersList(viewModelData: ViewDataSource)
  }
  struct ViewDataSource {
    let title: String
    let items: [CellModel]
  }
  
  struct CellModel {
    let name: String
    let imageName: String?
  }
  enum Route {
    case showCharacterDetail(id: String)
    case showError(model: ErrorModel)
  }
  
  struct DataSource {
    var characterList: [ResultList] = []
  }
}
