platform :ios, '13.0'
inhibit_all_warnings!

target 'MarvelAPIListSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelAPIListSample
  pod 'Alamofire', '5.4.0'
  pod 'Kingfisher'


  target 'MarvelAPIListSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAPIListSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
