//
//  CharacterDetailInteractor.swift
//  MarvelAPIListSample
//
//  Created by marco.iniguez.ollero on 6/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

typealias CharacterDetailInteractable = CharacterDetailBusinessLogic & CharacterDetailDataStore

protocol CharacterDetailBusinessLogic {
  
  func doRequest(_ request: CharacterDetailModel.Request)
}

protocol CharacterDetailDataStore {
  var dataSource: CharacterDetailModel.DataSource { get }
}

final class CharacterDetailInteractor: CharacterDetailDataStore {
  
  var dataSource: CharacterDetailModel.DataSource
  
  private var factory: CharacterDetailInteractorFactorable.InteractableFactory
  private var presenter: CharacterDetailPresentationLogic
  
  init(factory: CharacterDetailInteractorFactorable.InteractableFactory, viewController: CharacterDetailDisplayLogic?, dataSource: CharacterDetailModel.DataSource) {
    self.factory = factory
    self.dataSource = dataSource
    self.presenter = factory.makePresenter(viewController: viewController)
  }
}


// MARK: - CharacterDetailBusinessLogic
extension CharacterDetailInteractor: CharacterDetailBusinessLogic {
  
  func doRequest(_ request: CharacterDetailModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case .prepareCharactersDetail:
        self.prepareCharactersDetail()
      }
    }
  }
}


// MARK: - Private Zone
private extension CharacterDetailInteractor {
  
  func prepareCharactersDetail() {
    let service = factory.makeApiService()
      LoaderView.toggleUniversalLoadingView(true)
      service.getCharacterDetail(id: dataSource.characterId) { (result, _) in 
      LoaderView.toggleUniversalLoadingView(false)
      switch result {
      case let .success(list):
        if let data = list.data, let results = data.results, let item = results.first {
          self.presenter.presentResponse(.prepareCharactersDetail(data: item))
        }
        
      case .failure:
        let errorModel = ErrorHelper.createGenericError()
        self.presenter.presentResponse(.showError(model: errorModel))
      }
    }
    
  }
}
