//
//  CharacterDetailRouter.swift
//  MarvelAPIListSample
//
//  Created by marco.iniguez.ollero on 6/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CharacterDetailRouting {
  
  func routeTo(_ route: CharacterDetailModel.Route)
}

final class CharacterDetailRouter {
  
  private weak var viewController: UIViewController?
  
  init(viewController: UIViewController?) {
    self.viewController = viewController
  }
}


// MARK: - CharacterDetailRouting
extension CharacterDetailRouter: CharacterDetailRouting {
  
  func routeTo(_ route: CharacterDetailModel.Route) {
    DispatchQueue.main.async {
      switch route {
        
      case let .showError(model):
        self.showErrorAlert(viewModel: model)
        
      }
    }
  }
}


// MARK: - Private Zone
private extension CharacterDetailRouter {
  
  func showErrorAlert(viewModel: ErrorModel) {
    self.viewController?.showAlertWithCompletion(
      title: viewModel.title,
      message: viewModel.message,
      okTitle: viewModel.retryButtonTitle,
      cancelTitle: nil,
      completionBlock: { (done) in
        if done {
            if let vc = self.viewController as? CharacterDetailViewController {
              vc.errorRetryRequest()
            }
        }
      })
  }
}
