//
//  CharacterDetailPresenter.swift
//  MarvelAPIListSample
//
//  Created by marco.iniguez.ollero on 6/7/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol CharacterDetailPresentationLogic {
  func presentResponse(_ response: CharacterDetailModel.Response)
}

final class CharacterDetailPresenter {
  private weak var viewController: CharacterDetailDisplayLogic?
  
  init(viewController: CharacterDetailDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - CharacterDetailPresentationLogic
extension CharacterDetailPresenter: CharacterDetailPresentationLogic {
  
  func presentResponse(_ response: CharacterDetailModel.Response) {
    
    switch response {
      
    case let .prepareCharactersDetail(data):
      self.prepareCharactersDetail(data: data)
      
    case let .showError(model):
      self.viewController?.displayViewModel(.showError(model: model))
      
    }
  }
}


// MARK: - Private Zone
private extension CharacterDetailPresenter {
  
  func prepareCharactersDetail(data: ResultList) {
    let titleComics = "Comics"
    var itemsComics = [CharacterDetailModel.CellModel]()
    if let comics = data.comics, let items = comics.items {
      for item in items {
        if let name = item.name {
          itemsComics.append(CharacterDetailModel.CellModel(title: name))
        }
      }
    }
    let sectionComics = CharacterDetailModel.SectionModel(title: titleComics, items: itemsComics)
    
    let titleSeries = "Series"
    var itemsSeries = [CharacterDetailModel.CellModel]()
    if let series = data.series, let items = series.items {
      for item in items {
        if let name = item.name {
          itemsSeries.append(CharacterDetailModel.CellModel(title: name))
        }
      }
    }
    let sectionSeries = CharacterDetailModel.SectionModel(title: titleSeries, items: itemsSeries)
    
    let titleStories = "Stories"
    var itemsStories = [CharacterDetailModel.CellModel]()
    if let stories = data.stories, let items = stories.items {
      for item in items {
        if let name = item.name {
          itemsStories.append(CharacterDetailModel.CellModel(title: name))
        }
      }
    }
    let sectionStories = CharacterDetailModel.SectionModel(title: titleStories, items: itemsStories)
    
    let titleEvents = "Events"
    var itemsEvents = [CharacterDetailModel.CellModel]()
    if let events = data.events, let items = events.items {
      for item in items {
        if let name = item.name {
          itemsEvents.append(CharacterDetailModel.CellModel(title: name))
        }
      }
    }
    let sectionEvents = CharacterDetailModel.SectionModel(title: titleEvents, items: itemsEvents)
    
    var imageName: String?
    if let thumbnail = data.thumbnail, let path = thumbnail.path, let exten = thumbnail.exten {
      imageName = path + "." + exten
    }
    let viewData = CharacterDetailModel.ViewDataSource(
      title: data.name ?? "",
      imageName: imageName,
      sections: [sectionComics, sectionSeries, sectionStories, sectionEvents])
    viewController?.displayViewModel(.prepareCharactersDetail(viewModelData: viewData))
  }
}
